package team.project.entity;

import io.swagger.v3.oas.annotations.media.Schema;

import javax.persistence.*;
import java.util.Map;


/**
 * Main entity class for profiles - maps instance variables to DB table
 * A Profile is to be thought of as a physical-profile/general physical characteristics
 * accesses team_project schema
 * references profiles db table
 */
@Entity
@Table(name = "profiles")
@Schema(description = "Represents a set of bio data about an individual")
public class Profile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    @Schema(description = "Profile ID", example = "123")
    private int id;

    @Schema(description = "Profile Age (in years)", example = "38")
    @Column(name = "age")
    private int age;

    @Schema(description = "Profile Height (in inches)", example = "70")
    @Column(name = "height")
    private double height;

    @Schema(description = "Profile Weight (in pounds)", example = "165")
    @Column(name = "weight")
    private double weight;

    @Schema(description = "Profile Biological Sex", example = "male")
    @Column(name = "sexType")
    private String sexType;

    @Schema(description = "Profile Activity Modifier, which is used to estimate how many calories are burned per day based on activity level", example = "1.725")
    @Column(name = "activity")
    private double activity;

    @Schema(
            description = "A map of calculated health and nutrition metrics derived from profile data. Common keys include BMR (Basal Metabolic Rate), TDEE (Total Daily Energy Expenditure), and BMI (Body Mass Index).",
            example = "{\"BMR\": 1650.75, \"TDEE\": 2845.54, \"BMI\": 23.66}"
    )
    @Transient
    private Map<String, Double> calculations;


    //empty constructor
    public Profile() {}

    /**
     * Profile constructor
     * ID is excluded - ID is autogenerated in DB, prevents editing ID and causing integrity conflicts
     * @param age profile age
     * @param height profile height
     * @param weight profile weight
     * @param sexType profile sexType
     * @param activity profile activity
     */
    public Profile(int age, double height, double weight, String sexType, double activity) {
        this.age = age;
        this.height = height;
        this.weight = weight;
        this.sexType = sexType;
        this.activity = activity;
    }


    /**
     * GET method for ID
     * @return id
     */
    public int getId() {return id;}

    /**
     * SET method for ID
     * @param id id
     */
    public void setId(int id) {this.id = id;}

    /**
     * GET method for age
     * @return age
     */
    public int getAge() {return age;}

    /**
     * SET method for age
     * @param age age
     */
    public void setAge(int age) {this.age = age;}

    /**
     * GET method for height
     * @return height
     */
    public double getHeight() {return height;}

    /**
     * SET method for height
     * @param height height
     */
    public void setHeight(double height) {this.height = height;}

    /**
     * GET method for weight
     * @return weight
     */
    public double getWeight() {return weight;}

    /**
     * SET method for weight
     * @param weight weight
     */
    public void setWeight(double weight) {this.weight = weight;}

    /**
     * GET method for sexType
     * @return sexType
     */
    public String getSexType() {return sexType;}

    /**
     * SET method for sexType
     * @param sexType sexType
     */
    public void setSexType(String sexType) {this.sexType = sexType;}

    /**
     * GET method for activity levels
     * @return activity levels
     */
    public double getActivity() {return activity;}

    /**
     * SET method for activity levels
     * @param activity activity levels
     */
    public void setActivity(double activity) {this.activity = activity;}

    /**
     * GET method for calculations
     * @return calculations map
     */
    public Map<String, Double> getCalculations() {return calculations;}

    /**
     * SET method for calculations
     * @param calculations calculations map
     */
    public void setCalculations(Map<String, Double> calculations) {this.calculations = calculations;}
}
