package refactor;

import javax.persistence.*;


/**
 * Main entity class for profiles - maps instance variables to DB table
 * A Profile is to be thought of as a physical-profile/general physical characteristics
 * accesses team_project schema
 * references profiles db table
 */
@Entity
@Table(name = "profiles")
public class ProfileEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @Column(name = "age")
    private int age;

    @Column(name = "height")
    private double height;

    @Column(name = "weight")
    private double weight;

    @Column(name = "sex")
    private String sex;

    @Column(name = "activity")
    private double activity;


    //empty constructor
    public ProfileEntity() {}

    /**
     * Profile constructor
     * ID is excluded - ID is autogenerated in DB, prevents editing ID and causing integrity conflicts
     * @param age profile age
     * @param height profile height
     * @param weight profile weight
     * @param sex profile sex-type
     * @param activity profile activity
     */
    public ProfileEntity(int age, double height, double weight, String sex, double activity) {
        this.age = age;
        this.height = height;
        this.weight = weight;
        this.sex = sex;
        this.activity = activity;
    }


    /**
     * GET method for ID
     * @return id
     */
    public int getId() {return id;}

    /**
     * SET method for ID
     * @param id id
     */
    public void setId(int id) {this.id = id;}

    /**
     * GET method for age
     * @return age
     */
    public int getAge() {return age;}

    /**
     * SET method for age
     * @param age age
     */
    public void setAge(int age) {this.age = age;}

    /**
     * GET method for height
     * @return height
     */
    public double getHeight() {return height;}

    /**
     * SET method for height
     * @param height height
     */
    public void setHeight(double height) {this.height = height;}

    /**
     * GET method for weight
     * @return weight
     */
    public double getWeight() {return weight;}

    /**
     * SET method for weight
     * @param weight weight
     */
    public void setWeight(double weight) {this.weight = weight;}

    /**
     * GET method for sex-type
     * @return sex-type
     */
    public String getSex() {return sex;}

    /**
     * SET method for sex-type
     * @param sex sex-type
     */
    public void setSex(String sex) {this.sex = sex;}

    /**
     * GET method for activity levels
     * @return activity levels
     */
    public double getActivity() {return activity;}

    /**
     * SET method for activity levels
     * @param activity activity levels
     */
    public void setActivity(double activity) {this.activity = activity;}
}
